
server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication #RabbitMQ exchange name
          group: ${spring.application.name} #RabbitMQ queue name (exchange name + queue name = send-communication.message)
        emailsms-out-0:
          destination: communication-sent

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
